// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 03

#include "ui.h"
#include "driver/gpio.h"

void Lamp_on(lv_event_t * e)
{
	gpio_set_level(GPIO_NUM_18, 1);
}

void Lamp_off(lv_event_t * e)
{
	gpio_set_level(GPIO_NUM_18, 0);
}
