// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 03

#include "ui.h"

extern void app_lamp_set(int enabled);

void Lamp_on(lv_event_t * e)
{
    LV_UNUSED(e);
    app_lamp_set(1);
}

void Lamp_off(lv_event_t * e)
{
    LV_UNUSED(e);
    app_lamp_set(0);
}
