#include "Arduino.h"
#include "LovyanGFX_Driver.h"
#include <Wire.h>
#include <SPI.h>
#include "ui.h"
#include "lvgl.h"
#include <Crowbits_DHT20.h>

// Global display driver instance used by LVGL callbacks.
LGFX gfx;

// Temperature and humidity sensor on the I2C bus.
Crowbits_DHT20 dht20;

/*---------------------------------------------------------------
 * LVGL configuration
 * The lesson uses a small pair of draw buffers and updates the UI
 * with live sensor readings from the DHT20.
 *--------------------------------------------------------------*/
#define HOR_RES 320
#define VER_RES 480

// Two partial buffers keep the screen responsive without using a full
// frame buffer.
static uint16_t buf_1[HOR_RES * 20];
static uint16_t buf_2[HOR_RES * 20];

/**
 * @brief Return the millisecond tick source used by LVGL.
 *
 * @param None.
 * @return Current time in milliseconds.
 */
static uint32_t my_tick_get(void) {
    return millis();
}

/**
 * @brief Transfer one LVGL refresh rectangle to the LCD.
 *
 * @param disp LVGL display object requesting the flush.
 * @param area Dirty rectangle that should be updated.
 * @param px_map Pixel buffer generated by LVGL.
 * @return None.
 */
void my_disp_flush(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map) {
    uint32_t w = area->x2 - area->x1 + 1;
    uint32_t h = area->y2 - area->y1 + 1;
    
    gfx.startWrite();
    gfx.setAddrWindow(area->x1, area->y1, w, h);
    gfx.pushPixels(reinterpret_cast<uint16_t *>(px_map), w * h, true);
    gfx.endWrite();
    
    lv_display_flush_ready(disp);
}

// Stores the latest touch coordinate reported by the panel.
uint16_t touchX, touchY;

/**
 * @brief Report touch input to LVGL.
 *
 * @param indev LVGL input device object.
 * @param data Output structure filled with pointer state.
 * @return None.
 */
void my_touchpad_read(lv_indev_t *indev, lv_indev_data_t *data) {
  (void)indev;
  data->state = LV_INDEV_STATE_REL;
  if ( gfx.getTouch( &touchX, &touchY ) ) {
    data->state = LV_INDEV_STATE_PR;
    data->point.x = touchX;
    data->point.y = touchY;

    Serial.print( "Data x " );
    Serial.println( data->point.x );
    Serial.print( "Data y " );
    Serial.println( data->point.y );
  }
}

/**
 * @brief Update the temperature and humidity labels.
 *
 * The function throttles updates so the labels are not rewritten on
 * every loop iteration. The first call always pushes live readings to
 * the screen.
 *
 * @param None.
 * @return None.
 */
void set_dht_lvgl() {
    static uint32_t last_read_ms = 0;
    const uint32_t now = millis();
    if(last_read_ms != 0 && now - last_read_ms < 2000) return;
    last_read_ms = now;

    char DHT_buffer[6];
    int temp = (int)dht20.getTemperature();
    int humi = (int)dht20.getHumidity();

    snprintf(DHT_buffer, sizeof(DHT_buffer), "%d", temp);
    lv_label_set_text(ui_TempLabel1, DHT_buffer);

    memset(DHT_buffer, 0, sizeof(DHT_buffer));

    snprintf(DHT_buffer, sizeof(DHT_buffer), "%d", humi);
    lv_label_set_text(ui_HumiLabel2, DHT_buffer);
}

/**
 * @brief Initialize the sensor, display, touch input, and UI.
 *
 * @param None.
 * @return None.
 * @note Called once by the Arduino runtime after reset.
 */
void setup() {
    Serial.begin(115200);
    while(!Serial);
    Serial.println("\n\n[System] System starting...");

    Wire.begin(15, 16);
    delay(50);

    dht20.begin();

    pinMode(38, OUTPUT);
    digitalWrite(38, LOW);

    /*---------------------------------------------------------------
     * Start the LCD before attaching it to LVGL.
     *--------------------------------------------------------------*/
    gfx.begin();
    gfx.setRotation(0);
    gfx.setBrightness(128);
    digitalWrite(38, HIGH);

    lv_init();
    lv_tick_set_cb(my_tick_get);

    lv_display_t *display = lv_display_create(gfx.width(), gfx.height());
    lv_display_set_color_format(display, LV_COLOR_FORMAT_RGB565);
    lv_display_set_flush_cb(display, my_disp_flush);
    lv_display_set_buffers(display, buf_1, buf_2, sizeof(buf_1), LV_DISPLAY_RENDER_MODE_PARTIAL);

    lv_indev_t *touch_indev = lv_indev_create();
    lv_indev_set_type(touch_indev, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(touch_indev, my_touchpad_read);
    lv_indev_set_display(touch_indev, display);

    ui_init();

    Serial.println("[System] Initialization complete");
}

/**
 * @brief Update the labels and service LVGL.
 *
 * @param None.
 * @return None.
 */
void loop() {
    set_dht_lvgl();
    lv_timer_handler();
    delay(5);
}

extern "C" void app_main(void)
{
    initArduino();

    setup();

    while (true)
    {
        loop();
        delay(1);
    }
}
