// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 03

#include "ui.h"

void Lamp_on(lv_event_t * e)
{
	// Your code here
}

void Lamp_off(lv_event_t * e)
{
	// Your code here
}
