// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 03

#include "ui.h"

extern void set_lamp_state(bool enabled);

void Lamp_on(lv_event_t * e)
{
    set_lamp_state(true);
}

void Lamp_off(lv_event_t * e)
{
    set_lamp_state(false);
}
