// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 05

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_TempLabel1 = NULL;
lv_obj_t * ui_HumiLabel2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_background_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TempLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel1, -38);
    lv_obj_set_y(ui_TempLabel1, -62);
    lv_obj_set_align(ui_TempLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel1, "25");
    lv_obj_set_style_text_color(ui_TempLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiLabel2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumiLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiLabel2, -36);
    lv_obj_set_y(ui_HumiLabel2, 37);
    lv_obj_set_align(ui_HumiLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumiLabel2, "60");
    lv_obj_set_style_text_color(ui_HumiLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumiLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumiLabel2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    ui_TempLabel1 = NULL;
    ui_HumiLabel2 = NULL;

}
